# -*- coding: utf-8 -*-
"""Nested_Conditional_Statement.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KcoFEZ85uOZ5IJ_HvpZBxkrjESlpOM8C

For a given product demandis decided by number of people who attempt to buy through an online platform. if demand is greater than or equal to 5000, it is called HIGH DEMAND; if it is less than 5000 and more than or equal to 2000, the demand is called MODERATE; and is it LESS DEMAND, otherwise.
(Input is demand; output is type of demand).
"""

demand = int(input("Enter the demand : "))

if demand>= 5000:
  print("HIGH DEMAND")
elif demand<5000 and demand>= 2000:
  print("MODERATE DEMAND")
else :
  print("LESS DEMAND")

"""# Nested Condition.

1. demand.high(>=5000),low
2. suppy.high(>=5000), low
3. price: numbers
4. margin: 20%

Problem Statements:

if demand is high and supply is low, increase price by margin.

if demand is high and supplu is also high, don't change price.

if demand is low and supply is also low, dont change the price.

if demand is low and supply is high, decrease price by margin.
"""

demand = int(input('Enter demand'))
supply = int(input('Enter Supply'))
price = float(input('Enter your nominal price'))
margin = 0.20

if demand>=5000 and supply<5000:
  #increase price
  price = price * (1+margin)
  #price = price + (price*margin)  -- price + (price * 0.20)
  #  x   =   x   +   (x*m)
  #  x   =   x  (1 + m)
  #price = price * (1 + margin)    ---- hence proved.
  print(price)
elif demand>=5000 and supply>=5000:
  #dont change
  print(price)
elif demand<5000 and supply<5000:
  #dont change
  print(price)
elif demand<5000 and supply>=5000:
  #decrease price
  #price = price * (1-margin)
  print(price)

#with nested condition.


demand = int(input('Enter demand'))
supply = int(input('Enter Supply'))
price = float(input('Enter your nominal price'))
margin = 0.20

if demand>=5000:
  if supply>=5000:
  #dont change
    print(price)
  else:
  #increase price
    price = price * (1+margin)
  #price = price + (price*margin)  -- price + (price * 0.20)
  print(price)

else:
  if supply>=5000:
  #decrease price
    price = price * (1-margin)
    print(price)
  else:
  #dont change
    print(price)

"""Example.

1. if marks of maths>=70, physics>=70, chemistry>=50, allocate Group A
2. if marks of maths<70, physics<70, allocate Group B
3. if marks of maths<70, physics>=70, allocate Group C
4. if marks of maths>=70, physics<70, allocate Group D
5. if marks of maths>=70, physics>=70, chemistry<50, allocate Group E

"""

maths = int(input('Enter maths mark'))
physics = int(input('Enter physics marks'))
chemistry = int(input('Enter chemistry marks'))

if maths>=70:
  if physics>=70:
    if chemistry>=50:
      print("Group A")
    else:                  #chemistry
      print("Group E")
  else :                   #physics
    print("Group D")
else:                      #maths
  if physics<70:
    print("Group B")
  else :
    print("Group C")