# -*- coding: utf-8 -*-
"""Variables_operators.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vXxyNn-S63d8_BuxZ_oXRw0hkd5H_D4H

Todays Topics:


1.   Print Function
2.   Input Function
3.   Variables
4.   Type Function
5.   Operators
"""

#Variables
a=5
b=6
print(a-b)
print(a+b)
a*b

#input
c=input()

#type
a = 5 #int
b = 10.8 #float
c = True #boolean (True/False)
d = 'c = a + b' #string

#print
print(type(a))
print(type(b))
print(type(c))
print(type(d))

#operators
a = 10
b = 3
print(a)
print(b)

a + b #addition

a - b #subtraction

a * c #multiplication

a / b #division

a // b #floor division #quotient

a % b #modulo division #remainder

2 * 5.6 # 2.0 * 5.6 #typecasting

#multiple operators.
a=5
b=10
c=8
a + b + c

5 + 10 +  8

#high rank operator
#* / // %
#low rank operator
#+ -

a * b + c

c + a * b

(c + a) * b

(5 + 1)*(8 * 2)
#(6) * (16)
# 6 * 16

(5 + (2*1)) + (8 * 2)
#(5 + 2) + (16)
#(7) + (16)

((5+(2*1)) + (8*2) * 3) + 4
#((5 + 2) + (16) * 3) + 4
#((7) + (16) * 3) + 4
#(7 + 16 * 3) + 4
#(7 + 48) + 4
# 55 + 4